apiVersion: apps/v1
kind: Deployment
metadata:
  name: movieservice-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movieservice
  template:
    metadata:
      labels:
        app: movieservice
    spec:
      containers:
      - name: movieservice
        image: movieservice-main-movie-service
        imagePullPolicy: Never
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: movieservice-service
spec:
  type: NodePort
  selector:
    app: movieservice
  ports:
  - port: 80
    targetPort: 3001
    nodePort: 30008